apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-portfolio
  namespace: resume-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-portfolio
  template:
    metadata:
      labels:
        app: resume-portfolio
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 65532
      serviceAccountName: resume-portfolio
      containers:
        - name: resume-portfolio
          image: docker.io/joeriverhavert/golang-portfolio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE