---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-portfolio
  namespace: resume-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-portfolio
  template:
    metadata:
      labels:
        app: resume-portfolio
    spec:
      containers:
      - name: resume-portfolio
        image: docker.io/joeriverhavert/golang-portfolio:latest 
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: host-logs
          mountPath: /logs
      serviceAccountName: resume-portfolio
      volumes:
        - name: host-logs
          hostPath:
            path: /var/log/resume-portfolio
            type: DirectoryOrCreate