---
apiVersion: v1
kind: Service
metadata:
  name: golang-portfolio
  namespace: portfolio-system
spec:
  selector:
    app: golang-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
